M48
; DRILL file KiCad 10.0.6 date 2026-09-12T10:58:33
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-12T10:58:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X54.61Y-64.77
X54.61Y-133.35
X111.76Y-64.77
X111.76Y-133.35
M30
